  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Sobre mim"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Currículo"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "Publicações"
  weight = 510
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"

  [[main]]
  name = "Experiência"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/pt/imprint/"
