---
title: Forecsat at scale
author: Mateus Pereira
date: '2022-11-16'
slug: []
categories:
  - Time series
tags:
  - Time series
  - forecast
  - modeltime
Description: ''
Tags: []
Categories: []
DisableComments: no
---

Cada vez mais empresas previsam de previsões em centenas e até milhares de produtos, entretanto fazer previsões com qualidade não é tão fácil. Passei por situações assim algumas vezes e acho duas abordagens muito interessantes para essa atividade: `Nested Forecast` e o uso de ML em modelos globais. Nesse projeto <https://github.com/m-pereira/forecast-credit> aplico de forma prática esses conceitos, realizando previsões sobre o mercado de crédito para o próximo ano e explicando passo a passo os prós e contras de cada decisão tomada. Como já trabalhei em banco, prever crédito é uma tarefa importante, podendo assim aproveitar de uma alta do ciclo de crédito, ou se proteger de um ciclo de crédito em baixa.

Nested forecast não é nada mais que aplicar um modelo por entidade, mas isso é algo pesado computacionalmente




